### ISSUE TITLE
Hvordan kan vi dele utkast?

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-blog#14]
Artiklene våre vil kanskje skrives i Google Docs/Word i en tidlig fase, men forhåpentligvis utvikle seg til å være samarbeidsprosjekter mellom skribenter, designere og utviklere. I dag er man nødt til å kjøre Jekyll lokalt for å lese artikler som er under utvikling.

Hvordan kan vi best dele artikler som er under arbeid i en senere fase, hvor ikke bare tekst, men også design/visualisering/kode også skal vises fram?

Ideer mottas med takk!

**Comment by Andersos** [comment]
@jarib Jeg prøvde å se på deployeren men fikk ikke helt til å fungere. Mulig jeg er utålmodig og at den kommer ut snart men for meg virket det ikke som det var sånn rett frem og se status. 

Utifra lenken du postet som ser slik ut http://deploy.holderdeord.no/output/holderdeord/hdo-blog/gh-pages/2014-12-08/005705/3759141bb4693ae8e277925a9b7fd28a4a349de0.log
Ser det ut som det er repo, dato, et tall 005705 muligens bygg nummer så commiten 3759141bb4693ae8e277925a9b7fd28a4a349de0
Er dette repoet til den deployeren https://github.com/holderdeord/hdo-webhook-deployer ?

**Comment by jarib** [comment]
Ja, det er repoet. Deployment trigges når [dette bygget er ferdig](https://travis-ci.org/holderdeord/hdo-blog/builds/48650812), og dukker da opp i lista på http://deploy.holderdeord.no/.

**Comment by Andersos** [comment]
Ah, sweet! Utålmodige meg. Ser ut som Travis bygget står i kø.
